CREATE DATABASE RENT_A_CAR_CANELLA;

USE RENT_A_CAR_CANELLA;

CREATE TABLE AGENCIA(
	ID_AGENCIA INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE GARAJE(
	ID_GARAJE INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,

	AGENCIA_ID_AGENCIA INT NOT NULL FOREIGN KEY 
		REFERENCES AGENCIA(ID_AGENCIA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE VEHICULO (
	ID_VEHICULO INT PRIMARY KEY IDENTITY(1,1),
	MATRICULA VARCHAR(15) NOT NULL,
	MARCA VARCHAR(20) NOT NULL,
	COLOR VARCHAR(20) NOT NULL,
	ALQUILER MONEY NOT NULL,

	GARAJE_ID_GARAJE INT NOT NULL FOREIGN KEY 
		REFERENCES GARAJE(ID_GARAJE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE TIPO_USUARIO(
	ID_TU INT PRIMARY KEY IDENTITY(1,1),
	DESCRIPCION VARCHAR(10) NOT NULL,
);

CREATE TABLE USUARIO (
	ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	CORREO VARCHAR(50) NOT NULL,
	USUARIO VARCHAR(25) NOT NULL,
	CONTRASENIA VARCHAR(50) NOT NULL,

	TU_ID_TU INT NOT NULL FOREIGN KEY 
		REFERENCES TIPO_USUARIO(ID_TU) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE RESERVA(
	ID_RESERVA INT PRIMARY KEY IDENTITY(1,1),
	FECHA_PRESTAMO DATETIME NULL,
	FECHA_DEVOLUCION DATETIME NULL,
	TOTAL MONEY NOT NULL,

	USUARIO_ID_USUARIO INT NOT NULL FOREIGN KEY 
		REFERENCES USUARIO(ID_USUARIO) ON UPDATE CASCADE ON DELETE CASCADE,
	VEHICULO_ID_VEHICULO INT NOT NULL FOREIGN KEY 
		REFERENCES VEHICULO(ID_VEHICULO) ON UPDATE CASCADE ON DELETE CASCADE
);
